the_tower = User.create(name: "Adam")
christian = User.create(name: "King")
ric = User.create(name: "Eric")
jon = User.create(name: "Jon")
dickard = User.create(name: "Dick")

Score.create(quantity: 1000, user: the_tower)
Score.create(quantity: 1000, user: christian)
Score.create(quantity: 3000, user: ric)
Score.create(quantity: 2000, user: jon)
Score.create(quantity: 7000, user: dickard)
Score.create(quantity: 9000, user: ric)
Score.create(quantity: 1000, user: the_tower)
Score.create(quantity: 1000, user: jon)
Score.create(quantity: 4000, user: the_tower)
Score.create(quantity: 8000, user: christian)
Score.create(quantity: 5000, user: jon)
